sudo: false
language: python
matrix:
  include:
    - python: "3.5"
      env: LTD_MASON_BUILD=true
install:
  - pip install -r requirements.txt
  - pip install "ltd-mason>=0.2,<0.3"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd-mason-travis --html-dir _build/html
env:
  global:
    - LTD_MASON_BUILD=false  # disable builds in regular text matrix
    - LTD_MASON_PRODUCT="sqr-027"
    # Add AWS and LTD Keeper credentials as encrypted secrets here
    - secure: "QFQx5Cc728T2Zmtm7o8ef+SSpmfBi01YWxXMuTMCOwUbrgp8jwOkIW9eKZ/xaCNV95pR7t4RZJW8+A4kD5G04F/phw0S6j2L71WAcwo74yMFjb3f5+IyjwwDD1rSFPH+3vEPptXrH8lCjvmlfhU4YH1uHlEBxCdmEpVzVWpBEo5ZATTUlc7snOsjWhgeyRzuYhV2JxmEQ/muq7baLNTCKMYSvdQmYy4n3yO1iLz5mECdOJ6zkhNyfhGmlRPD7nqr7Dy3jy0r1itCgVfBDhoGAcvREgwTcWud8dUA+9wlbwtgEg2kF/KF8T5e4p0icFOlsp6jeAIR6kBpV/T1Cnzr+Ct9z/RkoES6AFe8o5KkbMdotH1BxYN6+97eWMV4fJ6Aij+Wu7PsBTGZLai3A+iffNlPAiA9VkY7r1eUm8kdIv4/qUWsVjE9MiGpZTLZcZHvLUN2Ts074S0zk5U/aO2Anj/LDm3RKeQvlpFMn1CXxTr29vTUpWS5gX9oNM3M7tTDf2CKw052jqkCPjEgrSwExncapTwXoWqIcUR7ii6anDQQM6ET993gEtlkRLoN+WFNR1oBFrjf3rN3GCxSSLh/4q5wMf9s8SSQnb3VjEjCfeXLK1zznGfe980xSpIr2cyhQ0PfKF9Hlp3LPvEDQcmzrjoEjhnwaalS6Q9k4yqRnUc="
    - secure: "ibzcTwQo7s2LL1Vj5syme+0My2PW/rRzzPR6mHfU48KOWvG7W6rL8EAQGq3m/wg7k+9xXczSgZGwoa/Yae91WGvXX1MIVZzbolAX/PmNpXEyVG47kXoNbDM84LdsYPnlTmP9fXgK3XY9FtOaJyHqqvuYZoUT6DSpRGpVmwjNKhCC9hy+xTk7X+BvwKfNMKdrAUAz6ibrldnWpruAOeaYYEfeqE0Pk+4C/RkWw5t8LaN+fvsvBLEaKoDW9g3qQj9ST3vXxiIKHZRaAQcXoaVNDIGdG3fiz/bOoYZzhSj1eyGe8vULmP58FVKFO0BJ2r/73bqTxOXdWhvIks0d55uvnHWBPOYTsBvMMfdbXL7sC7890V86aaNxh75/wb9SrmgIkNK+4x5+M4Lv7aVrzUR1nezWfU+KDfuwoVU7gN6z8Ao1a+ZOz09glTZgWFy9YuaZGvGsa9I+576hvDkqgxzzG1MIT20mRXcaiWHIQZbQU/SyhwehxSjfEQKTLpDTWblcxAtZAHSxC3j1JAwXlQMO/y7Lu88qGz4f2hN5dN9aE/CAIMHZ2AIdzuxD73gdf8tQ6lzxs31aQT7sKpb2PYdTnqBTxcHvPM9fY/4j3dOc01AreimCdzymLOL4PMfMm79Pjbys/S5lXsUcK9wIpdKJvIyiLplCgBHh3kTM7c9KO7w="
